[project]
name = "portfolio"
version = "0.1.0"
description = "My portfolio website made with Zensical."
readme = "README.md"
authors = [
    { name = "Wannes Vantorre", email = "vantorrewannes@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[dependency-groups]
dev = [
    "zensical>=0.0.67",
]
